//auth-apis
export const USER_LOGIN_LOADING = "USER_LOGIN_LOADING";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";

export const USER_PROFILE_LOADING = "USER_PROFILE_LOADING";
export const USER_PROFILE = "USER_PROFILE";
export const USER_PROFILE_FAILURE = "USER_PROFILE_FAILURE";

export const USER_SIGNUP_LOADING = "USER_SIGNUP_LOADING";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAILURE = "USER_SIGNUP_FAILURE";




export const FIND_FRIEND_LOADING = "FIND_FRIEND_LOADING";
export const FIND_FRIEND_SUCCESS = "FIND_FRIEND_SUCCESS";
export const FIND_FRIEND_FAILURE = "FIND_FRIEND_FAILURE";

export const GET_STORY_LOADING = "GET_STORY_LOADING";
export const GET_STORY_SUCCESS = "GET_STORY_SUCCESS";
export const GET_STORY_FAILURE = "GET_STORY_FAILURE";


export const POST_STORY_UPLOAD_LOADING = "POST_STORY_UPLOAD_LOADING";
export const POST_STORY_UPLOAD_SUCCESS = "POST_STORY_UPLOAD_SUCCESS";
export const POST_STORY_UPLOAD_FAILURE = "POST_STORY_UPLOAD_FAILURE";
